// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXRzC1tGVi1LUj4DLGsMuvKaIt2apuOw4',
    appId: '1:1014195525225:web:f30e280a39a73a359eb4f8',
    messagingSenderId: '1014195525225',
    projectId: 'workshop-gig-app',
    authDomain: 'workshop-gig-app.firebaseapp.com',
    storageBucket: 'workshop-gig-app.firebasestorage.app',
    measurementId: 'G-PP2HR0RMVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGcJOrp3t70lkRAtooflVBr9lAAYpihig',
    appId: '1:1014195525225:android:b0787776e716727d9eb4f8',
    messagingSenderId: '1014195525225',
    projectId: 'workshop-gig-app',
    storageBucket: 'workshop-gig-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAcycf3fFNK9SHyU5CrHZUq-rONDT-mjc',
    appId: '1:1014195525225:ios:d1a648565bf87bba9eb4f8',
    messagingSenderId: '1014195525225',
    projectId: 'workshop-gig-app',
    storageBucket: 'workshop-gig-app.firebasestorage.app',
    iosBundleId: 'com.example.workshopgigapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAcycf3fFNK9SHyU5CrHZUq-rONDT-mjc',
    appId: '1:1014195525225:ios:d1a648565bf87bba9eb4f8',
    messagingSenderId: '1014195525225',
    projectId: 'workshop-gig-app',
    storageBucket: 'workshop-gig-app.firebasestorage.app',
    iosBundleId: 'com.example.workshopgigapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXRzC1tGVi1LUj4DLGsMuvKaIt2apuOw4',
    appId: '1:1014195525225:web:b38ef1c2451f2d9d9eb4f8',
    messagingSenderId: '1014195525225',
    projectId: 'workshop-gig-app',
    authDomain: 'workshop-gig-app.firebaseapp.com',
    storageBucket: 'workshop-gig-app.firebasestorage.app',
    measurementId: 'G-M26257JNDZ',
  );

}